---
JsonSchemaAdjustedBySwaggerProperty:
  meta:
    filepath: './json_schema'
  # The following fixed_fields are taken from the JSON Schema definition but their definitions were adjusted to the OpenAPI Specification.
  fixed_fields:
    items:
      type: SchemaObject
    allOf:
      type: SchemaObject
    # This field definition is differenct from Document.
    # Autual Definition is like this:
    properties:
      type: CustomJsonSchemaObject
    # This field definition is differenct from Document.
    # Autual Definition is like this:
    additionalProperties:
      type: CustomJsonSchemaObject